import type { ThemeConfig } from 'antd';

/** Global + component tokens only — no `.ant-*` DOM overrides anywhere in the admin. */
export const adminTheme: ThemeConfig = {
  token: {
    colorPrimary: '#0f7f8d',
    colorInfo: '#0f7f8d',
    colorSuccess: '#16a34a',
    colorWarning: '#d97706',
    colorError: '#dc2626',
    colorBgLayout: '#f7f8fa',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBorder: '#d5d9e0',
    colorBorderSecondary: '#e7e9ee',
    colorText: '#191b21',
    colorTextSecondary: '#5a6472',
    colorTextTertiary: '#8b93a1',
    borderRadius: 8,
    borderRadiusLG: 10,
    borderRadiusSM: 6,
    fontFamily: '"Inter Variable", Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontFamilyCode: '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 13,
    controlHeight: 34,
    boxShadow: '0 1px 2px rgba(16, 24, 40, 0.06)',
    boxShadowSecondary: '0 1px 2px rgba(16, 24, 40, 0.06)',
  },
  components: {
    Layout: { headerBg: '#ffffff', siderBg: '#12141a', bodyBg: 'transparent', headerHeight: 64, headerPadding: '0 20px' },
    Menu: {
      itemBorderRadius: 8,
      itemMarginInline: 8,
      itemHeight: 38,
      darkItemBg: 'transparent',
      darkSubMenuItemBg: 'transparent',
      darkItemSelectedBg: 'rgba(15, 127, 141, 0.24)',
      darkItemHoverBg: 'rgba(255, 255, 255, 0.06)',
      darkItemColor: 'rgba(233, 236, 239, 0.68)',
      darkItemSelectedColor: '#ffffff',
    },
    Card: { borderRadiusLG: 10, paddingLG: 16 },
    Table: {
      headerBg: '#f2f4f7',
      headerColor: '#5a6472',
      headerSplitColor: 'transparent',
      rowHoverBg: '#e9f7f8',
      cellPaddingBlock: 8,
      borderColor: '#e7e9ee',
      headerBorderRadius: 8,
    },
    Button: { fontWeight: 500, primaryShadow: 'none', defaultShadow: 'none' },
  },
};
