"""site audit outbox

Revision ID: 0001
Revises: 
Create Date: 2026-07-11 20:19:46.780631
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actor_subject', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_actor', 'audit_events', ['actor_subject'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('integration_bindings',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('binding_type', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'binding_type', 'external_id', name='uq_integration_bindings_provider_type_external')
    )
    op.create_index('ix_integration_bindings_entity', 'integration_bindings', ['entity_type', 'entity_id'], unique=False)
    op.create_table('integration_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('aggregate_type', sa.Text(), nullable=False),
    sa.Column('aggregate_id', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_integration_outbox_event_id')
    )
    op.create_index('ix_integration_outbox_aggregate', 'integration_outbox', ['aggregate_type', 'aggregate_id'], unique=False)
    op.create_index('ix_integration_outbox_pending', 'integration_outbox', ['available_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('navigation_menus',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_navigation_menus_key_live', 'navigation_menus', ['key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('pages',
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('route_key', sa.Text(), nullable=False),
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("template_key IN ('home','treatment-index','treatment-detail','clinic-detail','article-index','article-detail','quiz','legal','offers-index','generic')", name='ck_pages_template_key'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_pages_path_live', 'pages', ['path'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_pages_route_key_live', 'pages', ['route_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('preview_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_preview_sessions_token_hash')
    )
    op.create_index('ix_preview_sessions_expires_at', 'preview_sessions', ['expires_at'], unique=False)
    op.create_table('site_links',
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('phone','whatsapp','email','social','review','booking','map')", name='ck_site_links_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_site_links_kind_label_live', 'site_links', ['kind', 'label'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('site_publications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('workspace_version', sa.BigInteger(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('activation_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(snapshot) = 'object'", name='ck_site_publications_snapshot_object'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_site_publications_version')
    )
    op.create_index('ix_site_publications_published_at', 'site_publications', ['published_at'], unique=False)
    op.create_table('integration_deliveries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('outbox_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outbox_id'], ['integration_outbox.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_deliveries_outbox', 'integration_deliveries', ['outbox_id'], unique=False)
    op.create_table('navigation_items',
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('target_page_id', sa.Uuid(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(target_page_id IS NOT NULL) OR (external_url IS NOT NULL)', name='ck_navigation_items_target'),
    sa.ForeignKeyConstraint(['menu_id'], ['navigation_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['navigation_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_navigation_items_menu', 'navigation_items', ['menu_id'], unique=False)
    op.create_index('ix_navigation_items_page', 'navigation_items', ['target_page_id'], unique=False)
    op.create_index('ix_navigation_items_parent', 'navigation_items', ['parent_id'], unique=False)
    op.create_table('page_sections',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name='ck_page_sections_payload_object'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_sections_page', 'page_sections', ['page_id'], unique=False)
    op.create_table('page_seo',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('canonical_path', sa.Text(), nullable=True),
    sa.Column('og_media_id', sa.Uuid(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_page_seo_page_live', 'page_seo', ['page_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('site_state',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('default_locale', sa.Text(), nullable=False),
    sa.Column('default_timezone', sa.Text(), nullable=False),
    sa.Column('workspace_version', sa.BigInteger(), nullable=False),
    sa.Column('active_publication_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_site_state_singleton'),
    sa.ForeignKeyConstraint(['active_publication_id'], ['site_publications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_state')
    op.drop_index('uq_page_seo_page_live', table_name='page_seo', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('page_seo')
    op.drop_index('ix_page_sections_page', table_name='page_sections')
    op.drop_table('page_sections')
    op.drop_index('ix_navigation_items_parent', table_name='navigation_items')
    op.drop_index('ix_navigation_items_page', table_name='navigation_items')
    op.drop_index('ix_navigation_items_menu', table_name='navigation_items')
    op.drop_table('navigation_items')
    op.drop_index('ix_integration_deliveries_outbox', table_name='integration_deliveries')
    op.drop_table('integration_deliveries')
    op.drop_index('ix_site_publications_published_at', table_name='site_publications')
    op.drop_table('site_publications')
    op.drop_index('uq_site_links_kind_label_live', table_name='site_links', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('site_links')
    op.drop_index('ix_preview_sessions_expires_at', table_name='preview_sessions')
    op.drop_table('preview_sessions')
    op.drop_index('uq_pages_route_key_live', table_name='pages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_pages_path_live', table_name='pages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('pages')
    op.drop_index('uq_navigation_menus_key_live', table_name='navigation_menus', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('navigation_menus')
    op.drop_index('ix_integration_outbox_pending', table_name='integration_outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index('ix_integration_outbox_aggregate', table_name='integration_outbox')
    op.drop_table('integration_outbox')
    op.drop_index('ix_integration_bindings_entity', table_name='integration_bindings')
    op.drop_table('integration_bindings')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
