"""clinics people

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-12 00:23:58.563900
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('address_line', sa.Text(), nullable=True),
    sa.Column('address_detail', sa.Text(), nullable=True),
    sa.Column('address_full', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('map_embed_url', sa.Text(), nullable=True),
    sa.Column('map_link_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','coming_soon','closed')", name='ck_clinics_status'),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name='ck_clinics_lat'),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name='ck_clinics_lng'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_clinics_slug_live', 'clinics', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('doctors',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('portrait_media_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_doctors_slug_live', 'doctors', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('admin_principal_clinics',
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject', 'clinic_id')
    )
    op.create_index('ix_admin_principal_clinics_clinic', 'admin_principal_clinics', ['clinic_id'], unique=False)
    op.create_index('ix_admin_principal_clinics_subject', 'admin_principal_clinics', ['subject'], unique=False)
    op.create_table('clinic_contacts',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('display_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('phone','whatsapp','email','booking')", name='ck_clinic_contacts_kind'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinic_contacts_clinic', 'clinic_contacts', ['clinic_id'], unique=False)
    op.create_table('clinic_faqs',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinic_faqs_clinic', 'clinic_faqs', ['clinic_id'], unique=False)
    op.create_table('clinic_hours',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_clinic_hours_weekday'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_clinic_hours_clinic_weekday_live', 'clinic_hours', ['clinic_id', 'weekday'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('clinic_transit_items',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinic_transit_clinic', 'clinic_transit_items', ['clinic_id'], unique=False)
    op.create_table('doctor_clinics',
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'clinic_id')
    )
    op.create_index('ix_doctor_clinics_clinic', 'doctor_clinics', ['clinic_id'], unique=False)
    op.create_index('ix_doctor_clinics_doctor', 'doctor_clinics', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctor_clinics_doctor', table_name='doctor_clinics')
    op.drop_index('ix_doctor_clinics_clinic', table_name='doctor_clinics')
    op.drop_table('doctor_clinics')
    op.drop_index('ix_clinic_transit_clinic', table_name='clinic_transit_items')
    op.drop_table('clinic_transit_items')
    op.drop_index('uq_clinic_hours_clinic_weekday_live', table_name='clinic_hours', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('clinic_hours')
    op.drop_index('ix_clinic_faqs_clinic', table_name='clinic_faqs')
    op.drop_table('clinic_faqs')
    op.drop_index('ix_clinic_contacts_clinic', table_name='clinic_contacts')
    op.drop_table('clinic_contacts')
    op.drop_index('ix_admin_principal_clinics_subject', table_name='admin_principal_clinics')
    op.drop_index('ix_admin_principal_clinics_clinic', table_name='admin_principal_clinics')
    op.drop_table('admin_principal_clinics')
    op.drop_index('uq_doctors_slug_live', table_name='doctors', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('doctors')
    op.drop_index('uq_clinics_slug_live', table_name='clinics', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('clinics')
    # ### end Alembic commands ###
