"""catalog offers

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-12 00:32:23.498411
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('badge', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'RON'"), nullable=False),
    sa.Column('starts_at', sa.Text(), nullable=True),
    sa.Column('ends_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='ck_offers_currency'),
    sa.CheckConstraint("status IN ('draft','active','archived')", name='ck_offers_status'),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at', name='ck_offers_dates'),
    sa.CheckConstraint('old_amount IS NULL OR old_amount >= 0', name='ck_offers_old_nonneg'),
    sa.CheckConstraint('price_amount IS NULL OR price_amount >= 0', name='ck_offers_price_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_offers_slug_live', 'offers', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('partners',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=True),
    sa.Column('badge', sa.Text(), nullable=True),
    sa.Column('logo_media_id', sa.Uuid(), nullable=True),
    sa.Column('rights_note', sa.Text(), nullable=True),
    sa.Column('link_url', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partners_position', 'partners', ['position'], unique=False)
    op.create_table('technologies',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_technologies_position', 'technologies', ['position'], unique=False)
    op.create_table('treatment_categories',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_treatment_categories_slug_live', 'treatment_categories', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('offer_clinics',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'clinic_id')
    )
    op.create_index('ix_offer_clinics_clinic', 'offer_clinics', ['clinic_id'], unique=False)
    op.create_index('ix_offer_clinics_offer', 'offer_clinics', ['offer_id'], unique=False)
    op.create_table('offer_features',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offer_features_offer', 'offer_features', ['offer_id'], unique=False)
    op.create_table('treatments',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail_markdown', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('visits', sa.Text(), nullable=True),
    sa.Column('anesthesia', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['treatment_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatments_category', 'treatments', ['category_id'], unique=False)
    op.create_index('uq_treatments_slug_live', 'treatments', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('clinic_treatments',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('treatment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('clinic_id', 'treatment_id')
    )
    op.create_index('ix_clinic_treatments_clinic', 'clinic_treatments', ['clinic_id'], unique=False)
    op.create_index('ix_clinic_treatments_treatment', 'clinic_treatments', ['treatment_id'], unique=False)
    op.create_table('offer_treatments',
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('treatment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'treatment_id')
    )
    op.create_index('ix_offer_treatments_offer', 'offer_treatments', ['offer_id'], unique=False)
    op.create_index('ix_offer_treatments_treatment', 'offer_treatments', ['treatment_id'], unique=False)
    op.create_table('treatment_faqs',
    sa.Column('treatment_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatment_faqs_treatment', 'treatment_faqs', ['treatment_id'], unique=False)
    op.create_table('treatment_prices',
    sa.Column('treatment_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('price_kind', sa.Text(), server_default=sa.text("'exact'"), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('old_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), server_default=sa.text("'RON'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='ck_treatment_prices_currency'),
    sa.CheckConstraint("price_kind IN ('exact','from','range','on_request')", name='ck_treatment_prices_kind'),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name='ck_treatment_prices_amount_nonneg'),
    sa.CheckConstraint('amount_max IS NULL OR amount IS NULL OR amount_max >= amount', name='ck_treatment_prices_range_ordered'),
    sa.CheckConstraint('amount_max IS NULL OR amount_max >= 0', name='ck_treatment_prices_amount_max_nonneg'),
    sa.CheckConstraint('old_amount IS NULL OR old_amount >= 0', name='ck_treatment_prices_old_nonneg'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatment_prices_clinic', 'treatment_prices', ['clinic_id'], unique=False)
    op.create_index('ix_treatment_prices_treatment', 'treatment_prices', ['treatment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_treatment_prices_treatment', table_name='treatment_prices')
    op.drop_index('ix_treatment_prices_clinic', table_name='treatment_prices')
    op.drop_table('treatment_prices')
    op.drop_index('ix_treatment_faqs_treatment', table_name='treatment_faqs')
    op.drop_table('treatment_faqs')
    op.drop_index('ix_offer_treatments_treatment', table_name='offer_treatments')
    op.drop_index('ix_offer_treatments_offer', table_name='offer_treatments')
    op.drop_table('offer_treatments')
    op.drop_index('ix_clinic_treatments_treatment', table_name='clinic_treatments')
    op.drop_index('ix_clinic_treatments_clinic', table_name='clinic_treatments')
    op.drop_table('clinic_treatments')
    op.drop_index('uq_treatments_slug_live', table_name='treatments', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_treatments_category', table_name='treatments')
    op.drop_table('treatments')
    op.drop_index('ix_offer_features_offer', table_name='offer_features')
    op.drop_table('offer_features')
    op.drop_index('ix_offer_clinics_offer', table_name='offer_clinics')
    op.drop_index('ix_offer_clinics_clinic', table_name='offer_clinics')
    op.drop_table('offer_clinics')
    op.drop_index('uq_treatment_categories_slug_live', table_name='treatment_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('treatment_categories')
    op.drop_index('ix_technologies_position', table_name='technologies')
    op.drop_table('technologies')
    op.drop_index('ix_partners_position', table_name='partners')
    op.drop_table('partners')
    op.drop_index('uq_offers_slug_live', table_name='offers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('offers')
    # ### end Alembic commands ###
