"""editorial legal quiz

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-12 00:37:46.531971
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('reviewed_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','needs_review','published','archived')", name='ck_articles_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_articles_slug_live', 'articles', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('ebooks',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_media_id', sa.Uuid(), nullable=True),
    sa.Column('download_media_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ebooks_slug_live', 'ebooks', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('legal_documents',
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('version_label', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('gdpr','privacy','terms','cookies')", name='ck_legal_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_documents_type', 'legal_documents', ['doc_type'], unique=False)
    op.create_table('news_items',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','needs_review','published','archived')", name='ck_news_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_news_slug_live', 'news_items', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('quizzes',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_quizzes_slug_live', 'quizzes', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('quiz_questions',
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_questions_quiz', 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('reviews',
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','needs_review','published','archived')", name='ck_reviews_status'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_clinic', 'reviews', ['clinic_id'], unique=False)
    op.create_table('case_studies',
    sa.Column('treatment_id', sa.Uuid(), nullable=True),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_media_id', sa.Uuid(), nullable=True),
    sa.Column('after_media_id', sa.Uuid(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('consent_state', sa.Text(), server_default=sa.text("'none'"), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("consent_state IN ('none','pending','approved','revoked')", name='ck_case_consent'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_studies_clinic', 'case_studies', ['clinic_id'], unique=False)
    op.create_index('ix_case_studies_treatment', 'case_studies', ['treatment_id'], unique=False)
    op.create_table('quiz_options',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_options_question', 'quiz_options', ['question_id'], unique=False)
    op.create_table('quiz_result_bands',
    sa.Column('quiz_id', sa.Uuid(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('cta_treatment_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_score >= min_score', name='ck_quiz_band_range'),
    sa.ForeignKeyConstraint(['cta_treatment_id'], ['treatments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_result_bands_quiz', 'quiz_result_bands', ['quiz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_result_bands_quiz', table_name='quiz_result_bands')
    op.drop_table('quiz_result_bands')
    op.drop_index('ix_quiz_options_question', table_name='quiz_options')
    op.drop_table('quiz_options')
    op.drop_index('ix_case_studies_treatment', table_name='case_studies')
    op.drop_index('ix_case_studies_clinic', table_name='case_studies')
    op.drop_table('case_studies')
    op.drop_index('ix_reviews_clinic', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_quiz_questions_quiz', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index('uq_quizzes_slug_live', table_name='quizzes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('quizzes')
    op.drop_index('uq_news_slug_live', table_name='news_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('news_items')
    op.drop_index('ix_legal_documents_type', table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index('uq_ebooks_slug_live', table_name='ebooks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('ebooks')
    op.drop_index('uq_articles_slug_live', table_name='articles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('articles')
    # ### end Alembic commands ###
