"""media assets

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-12 00:46:13.852945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('media_kind', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('focal_x', sa.Float(), nullable=True),
    sa.Column('focal_y', sa.Float(), nullable=True),
    sa.Column('rights_note', sa.Text(), nullable=True),
    sa.Column('privacy_class', sa.Text(), server_default=sa.text("'public'"), nullable=False),
    sa.Column('readiness', sa.Text(), server_default=sa.text("'uploading'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_kind IN ('image','document')", name='ck_media_kind'),
    sa.CheckConstraint("privacy_class IN ('public','case_image')", name='ck_media_privacy'),
    sa.CheckConstraint("readiness IN ('uploading','ready','quarantined','failed')", name='ck_media_readiness'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_assets_checksum', 'media_assets', ['sha256'], unique=False)
    op.create_index('ix_media_assets_privacy', 'media_assets', ['privacy_class'], unique=False)
    op.create_table('content_media_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('usage', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_media_links_asset', 'content_media_links', ['asset_id'], unique=False)
    op.create_index('ix_content_media_links_entity', 'content_media_links', ['entity_type', 'entity_id'], unique=False)
    op.create_table('media_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.Text(), nullable=True),
    sa.Column('obtained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_consents_asset', 'media_consents', ['asset_id'], unique=False)
    op.create_table('media_delivery_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_delivery_blocks_asset', 'media_delivery_blocks', ['asset_id'], unique=False)
    op.create_table('media_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('variant', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'variant', name='uq_media_variants_asset_variant')
    )
    op.create_index('ix_media_variants_asset', 'media_variants', ['asset_id'], unique=False)
    op.create_table('publication_media',
    sa.Column('publication_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['publication_id'], ['site_publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'asset_id')
    )
    op.create_index('ix_publication_media_asset', 'publication_media', ['asset_id'], unique=False)
    op.create_foreign_key('fk_articles_cover_media_id', 'articles', 'media_assets', ['cover_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_case_studies_after_media_id', 'case_studies', 'media_assets', ['after_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_case_studies_before_media_id', 'case_studies', 'media_assets', ['before_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_doctors_portrait_media_id', 'doctors', 'media_assets', ['portrait_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ebooks_cover_media_id', 'ebooks', 'media_assets', ['cover_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ebooks_download_media_id', 'ebooks', 'media_assets', ['download_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_news_items_media_id', 'news_items', 'media_assets', ['media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_page_seo_og_media_id', 'page_seo', 'media_assets', ['og_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_partners_logo_media_id', 'partners', 'media_assets', ['logo_media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_quiz_options_media_id', 'quiz_options', 'media_assets', ['media_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_technologies_media_id', 'technologies', 'media_assets', ['media_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_technologies_media_id', 'technologies', type_='foreignkey')
    op.drop_constraint('fk_quiz_options_media_id', 'quiz_options', type_='foreignkey')
    op.drop_constraint('fk_partners_logo_media_id', 'partners', type_='foreignkey')
    op.drop_constraint('fk_page_seo_og_media_id', 'page_seo', type_='foreignkey')
    op.drop_constraint('fk_news_items_media_id', 'news_items', type_='foreignkey')
    op.drop_constraint('fk_ebooks_download_media_id', 'ebooks', type_='foreignkey')
    op.drop_constraint('fk_ebooks_cover_media_id', 'ebooks', type_='foreignkey')
    op.drop_constraint('fk_doctors_portrait_media_id', 'doctors', type_='foreignkey')
    op.drop_constraint('fk_case_studies_before_media_id', 'case_studies', type_='foreignkey')
    op.drop_constraint('fk_case_studies_after_media_id', 'case_studies', type_='foreignkey')
    op.drop_constraint('fk_articles_cover_media_id', 'articles', type_='foreignkey')
    op.drop_index('ix_publication_media_asset', table_name='publication_media')
    op.drop_table('publication_media')
    op.drop_index('ix_media_variants_asset', table_name='media_variants')
    op.drop_table('media_variants')
    op.drop_index('ix_media_delivery_blocks_asset', table_name='media_delivery_blocks')
    op.drop_table('media_delivery_blocks')
    op.drop_index('ix_media_consents_asset', table_name='media_consents')
    op.drop_table('media_consents')
    op.drop_index('ix_content_media_links_entity', table_name='content_media_links')
    op.drop_index('ix_content_media_links_asset', table_name='content_media_links')
    op.drop_table('content_media_links')
    op.drop_index('ix_media_assets_privacy', table_name='media_assets')
    op.drop_index('ix_media_assets_checksum', table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
